### ISSUE TITLE
[NEW/MISSING INFO] Get a burner phone

### ISSUE THREAD

**Issue by exv3** [AnonymousPlanet/thgtoa#14]
# Please follow these steps first:

- [x] Checked the issues (open and closed) for past discussion on the issue
- [x] Fact checked your information

### New/Missing Information:

"This is rather easy. Leave your smartphone off or power it off before leaving."

It's better to leave your phone at home but **leave it powered on** because if anything goes wrong near your area (murder case for example) then the law enforcement will start an investigation and check telecom (BTS) logs and you might become a suspect because for some strange reason your phone was **turned off** in the approximately time of the murder.

_"From what we see in the logs your phone is almost always turned on so why on this date at this time did you turn it off for over two hours? Doesn't it seem a little bit strange? Can you tell us where were you at this time? Do you have any witnesses?"_

Once an investigator officer said that when suspected person turns off his phone then he goes do illegal things.
It might be 1 case of a million but still it might be relevant to people who live in cities where there is high crime rate.

**Comment by AnonymousPlanet** [comment]
Yes this is recommended in the last part of the guide (OPSEC tips):

"•	When conducting sensitive activities, consider leaving your smart devices at home online and doing something (watching YouTube/Netflix or something similar) instead of taking them with you powered off. This will mitigate tracking efforts but also create digital traces that could indicate you were at home. "

But I agree it should also be said earlier. I will fix this in the next release.

Thank you.

**Comment by AnonymousPlanet** [comment]
This has been addressed in v0.7.0 with earlier warnings in various sections.
