### ISSUE TITLE
[NEW/MISSING INFO] I think this project needs to be improved

### ISSUE THREAD

**Issue by alaskasquirrel** [AnonymousPlanet/thgtoa#25]
[Linux Kodachi The Secure OS](https://www.digi77.com/linux-kodachi)

[GrapheneOS](https://grapheneos.org) is a privacy and security focused mobile OS with Android app compatibility as a non-profit open source project.

[Scoop](https://scoop.sh/) A command-line installer for Windows.

**Comment by AnonymousPlanet** [comment]
I mean scoop has nothing to do with anonymity/privacy in itself? I would argue Choco is much better for managing various apps but unfortunately does not work over Tor. Scoop in the context of my guide would just be useful to install Python/Git. But sure I can mention it.

I'm well aware of the existence of GrapheneOS and CalyxOS but while they're very interesting for privacy, I do not see their purpose/usefulness with Anonymity. None of them allow for IMEI randomization and are officially limited to a small subset of phones (mainly Pixel phones). My guide stands by its recommendation not to use a smartphone in the context of Anonymity opsec. 

Linux Kodachi is interesting and I'll consider the suggestion!

**Comment by AnonymousPlanet** [comment]
As for Kodachi Linux, and after digging a bit:

Things that worries me:

- Unclear website UX and no clear dedicated project site
- Gap between releases are huge sometimes around a year (from v6 to v7 for instance)
- Unclear source code access? The GitHub repository doesn't seem to have the latest releases. Where is it? Latest release is dated 16.04.2021 yet their GitHub repository is unmaintained since early 2020 (to which they point for the source code in their documentation).

For reference:

- https://www.reddit.com/r/TOR/comments/msot4m/linux_kodachi_os_secure_and_privacy_os/
- https://distrowatch.com/dwres.php?resource=ratings&distro=kodachi

I'm going to pass on Kodachi until it becomes more "mature", has better documentation and community support. Didn't pass my "Trust but verify" threshold. Sorry.
