### ISSUE TITLE
Overwriting of all files with each release

### ISSUE THREAD

**Issue by sigseg5** [AnonymousPlanet/thgtoa#27]
I am in translating the manual into another language, but you completely overwriting all the files, which makes it impossible to synchronize changes. It would be great if you create commits with a real change history, so that other people can track which chapters and files have changed with certain lines. After each release it is confusing to see something like "Showing with 13,464 additions and 0 deletions" in the tag comparison.

**Comment by AnonymousPlanet** [comment]
Shouldn't we try to use a better system for translation such as transifex? or weblate? I'm just not familiar enough with any of these tools to implement them atm. 

I understand the issue you're having tho. I'll consider it for the sake of translation.

**Comment by AnonymousPlanet** [comment]
Would you mind creating a transifex account or communicate me an e-mail privately so I can invite you to collaborate on transifex for a small trial ? I think they might manage the diff much better than doing this manually through github ...

**Comment by sigseg5** [comment]
done

**Comment by AnonymousPlanet** [comment]
From what I've seen, Transifex auto updates the guide.md from the English source and should keep already translated bits. We need to double check this with next release.

**Comment by AnonymousPlanet** [comment]
Ideally as well .. it would be nice to have third-party reviewers to review the translation. I gave you the reviewer role which should allow you to translate and review I guess?

**Comment by sigseg5** [comment]
Yep, I can translate and review changes now. Please add `README.md` as well, it also needs translation. Moreover, we need to do something with the `default.html` file, we need some changes there like `<html lang>` and a couple of lines in English. It would be good to generate pages for individual languages based on different templates.

**Comment by AnonymousPlanet** [comment]
I'm willing to allow translation through transifex and will add readme.md. I will also reference your repository within the readme when it's done. However I will not integrate those into my repository (yet) until there are reviewers. Otherwise I cannot verify the translation for accuracy and cannot vouch for them directly. I have no clue how accurate the translation is and it's not wise to base myself on only one translator/reviewer.

**Comment by sigseg5** [comment]
Deal!

**Comment by AnonymousPlanet** [comment]
Just did an updatte ... tell me if it messed up your side on transifex ... hopefully not

**Comment by sigseg5** [comment]
It's works, but I can't get any notification about changes. Now I added translation for `You want to understand the current state of online privacy and anonymity not necessarily get too technical about it: Just read the…`, can you correct links in this string now? I'd like to check does I get any notifications about translation updates at this situation.

**Comment by sigseg5** [comment]
You fixed `GGP` to `GPG`, innit?

**Comment by AnonymousPlanet** [comment]
No I fixed all your strings but I'm not sure about the frequency transifex does the automatic update from the source.

**Comment by AnonymousPlanet** [comment]
I forced an update manually :) Please check

**Comment by AnonymousPlanet** [comment]
As per Transifex documentation: "Transifex will check that URL for updates 4 times per day (every 6 hours) and if there are any changes to the file, it'll fetch the file and update the resource in Transifex. Because the check happens 4 times a day, there may be a delay between when you update a file and when Transifex detects the changes. The updated resource will automatically be available to your translators and reviewers."

**Comment by sigseg5** [comment]
Nice, I got update and I can see changes. I think that it's enough to create quality translation. P.S. If I was founded any troubles in original text I'll open issue at Transifex.

**Comment by AnonymousPlanet** [comment]
Since this is resolving the issue for translations at least :) I'm closing this one :)
