### ISSUE TITLE
[LINK/REFERENCE] Git history

### ISSUE THREAD

**Issue by jtagcat** [AnonymousPlanet/thgtoa#9]
Can't diff with previous revision :(

**Comment by AnonymousPlanet** [comment]
This is intended at the moment. Only the latest up-to-date version is meant to stay online. But I will work to improve the changelog tho I promise. You can still find some older versions on the waybackmachine. 

https://web.archive.org/web/2020*/https://anonymousplanet.github.io/thgtoa/guide.html

**Comment by jtagcat** [comment]
archive.org doesn't let you diff that easily. Commits in not HEAD of the branch don't stay online (on the site), they are not displayed unless specifically asked for.

Correct me if I'm wrong. I might not see a perspective you see.

**Comment by AnonymousPlanet** [comment]
You're not wrong ... but this is how I intend to keep it right now ...  The problem is that I add/change and re-number a lot of references and do plenty of very small commits all the time locally. This causes all endnotes reference numbers to change all through the document every time I change a reference (and therefore cause the whole document to change making a diff difficult to read anyway) and I don't want to deal with that right now so instead I'm just doing a clean-up commit each time (checkout, new temp branch, add current version, delete main, rename temp branch to main).

Instead I plan to focus on providing a better more precise changelog and keep the commit history clean for now. Maybe I'll change this when the document is more "mature" and has less issues to fix. Right now there are still lots of things I need to fix.

**Comment by jtagcat** [comment]
It seems that you haven't played with git a ton. Keeping commits small is great, well done!

The First step would be to always make changes on a new branch (like you already have, on your temporary branch). When committing straight to main, this is not needed, but its good practice to touch main as little as possible.

If you fear vim and git, you may use the GitLens extension on VSCode, and configure VSC as the default mergetool (and difftool).

Back to git. If you only do it locally: `git rebase -i origin/HEAD`.  
Rebase allows you to modify commits (but beware, pushing, then rebasing, you can only force-push; making it hard to collaborate with other persons).  
`-i` means interactive (you want to change something here), the last part specifies what to rebase. `origin` is the default remote name aka GitHub. `HEAD` says to get the last commit, that's on gh, and rebase up to that.

This is all just to say, we'll combine everything together, squash.

You want to either 'keep' or reword the earliest commit. All others you may choose to squash.
![image](https://user-images.githubusercontent.com/38327267/104374361-b2f6e380-5519-11eb-8187-da6dd3b07bb9.png)

Now, I'd actually advise against squashing, and keeping the commits small. This allows others to quickly understand part of the change they're interested in.¹

You may choose to push local changes only if ready, and you can make releases.²

You can compare with the last release (never minding the small commits in between).
![image](https://user-images.githubusercontent.com/38327267/104374757-416b6500-551a-11eb-9748-f720fef706e0.png)

¹ I understand pushing small commits may not be the optimal for this repo. Keep commits per-release, or per-paragraph. I don't care about the granularity, it's your choice.

² As you said, references change and mix up. You may keep a dev branch (with small commits), merging commits per-release to main as well.

Also see: https://git-rebase.io

**Comment by AnonymousPlanet** [comment]
Thx for all the info! I'll consider all of it!
